# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - serenity-v0.6.x

pool:
  vmImage: 'ubuntu-16.04'

container: 'rust:latest'
steps:
  - script: cargo build --all
    displayName: Run build
