[package]
name = "zero2_rs"
version = "0.5.2"
authors = ["Youssef Habri <youssef.habri@gmail.com>"]
edition = "2018"

[profile.dev]
incremental = true

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true

[dependencies]
chrono = "0.4"
dissolve = "0.2"
dotenv = "0.15"
indexmap = "1.3"
lazy_static = "1.4"
libmath = "0.2"
log = "0.4"
time = "0.1"
rand = "0.7"
regex = "1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
rust-embed = "5.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sys-info = "0.7"
sysinfo = "0.14"
serenity = "0.8"

[dependencies.fern]
version = "0.6"
features = ["colored"]

[dependencies.diesel]
version = "1.0.0"
features = ["postgres", "chrono", "r2d2"]

[dependencies.urbandictionary]
git = "https://github.com/youssefhabri/urbandictionary.rs"

# [patch.crates-io]
# openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }
