[package]
name = "zero2_rs"
version = "0.5.0"
authors = ["Youssef Habri <youssef.habri@gmail.com>"]
edition = "2018"

[profile.dev]
incremental = true

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true

[dependencies]
chrono = "0.4"
dotenv = "0.14"
html5ever = "0.24"
indexmap = "1.1"
lazy_static = "1.4"
libmath = "0.2"
log = "0.4"
time = "0.1"
tendril = "0.4"
rand = "0.7"
reqwest = "0.9"
rust-embed = "5.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sys-info = "0.5"
sysinfo = "0.9"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"

[dependencies.diesel]
version = "1.4"
features = ["postgres", "chrono", "r2d2"]

[dependencies.fern]
version = "0.5"
features = ["colored"]

[dependencies.regex]
version = "1.3"
default-features = false
features = ["std"]

[dependencies.urbandictionary]
git = "https://github.com/youssefhabri/urbandictionary.rs"

# [patch.crates-io]
# openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }
